questions =  [
    {"id": 0, "question": "In a capitalist system, hard work is by far the greatest determiner of individual success.", "effects": {"right": 1}},
    {"id": 1, "question": "A market economy is the most effective way to deal with scarcity.", "effects": {"right": 1}},
    {"id": 2, "question": "Equality of oppurtunity to succeed and fail should be guaranteed as a human right.", "effects": {"right": 1}},
    {"id": 3, "question": "Public schools do not benefit society.", "effects": {"right": 1}},
    {"id": 4, "question": "Selfishness is a virtue.", "effects": {"right": 1}},
    {"id": 5, "question": "Free trade is a positive in the modern world.", "effects": {"right": 1}},
    {"id": 6, "question": "The value of a product is entirely reliant on the demand for it.", "effects": {"right": 1}},
    {"id": 7, "question": "There is no such thing as a non-essential business in a capitalist soceity, as the market decides what is and isn't essential.", "effects": {"right": 1}},
    {"id": 8, "question": "The existance of private property benefits the rich exclusively.", "effects": {"right": -1}},
    {"id": 9, "question": "The practice of usury should be banned.", "effects": {"right": -1}},
    {"id": 10, "question": "The Capitalists will sell us the rope with which we will hang them.", "effects": {"right": -1}},
    {"id": 11, "question": "There should be a cap on people's wealth.", "effects": {"right": -1}},
    {"id": 12, "question": "Wage labour is a form of slavery.", "effects": {"right": -1}},
    {"id": 13, "question": "Affirmative action for the poor would improve society.", "effects": {"right": -1}},
    {"id": 14, "question": "A classless society is a realistic goal.", "effects": {"right": -1}},
    {"id": 15, "question": "Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists.", "effects": {"auth": 1}},
    {"id": 16, "question": "People who burn the flag should be serverly punished.", "effects": {"auth": 1}},
    {"id": 17, "question": "People who support a foreign nation over ours should be deported.", "effects": {"auth": 1}},
    {"id": 18, "question": "An ideal nation would be commited to regime change across the world.", "effects": {"auth": 1}},
    {"id": 19, "question": "All of our efforts should first and foreost be directed towards a consolidation of power.", "effects": {"auth": 1}},
    {"id": 20, "question": "If a government cannot protect its people from violence, than it is illegitimate.", "effects": {"auth": 1}},
    {"id": 21, "question": "Police officers should be able to carry guns.", "effects": {"auth": 1}},
    {"id": 22, "question": "Labour camps, such as those of the Soviet Union or Nazi Germany, are a good idea.", "effects": {"auth": 1}},
    {"id": 23, "question": "To conquer a nation, first disarm its citizens.", "effects": {"auth": -1}},
    {"id": 24, "question": "Rights are inalienable and do not come from governments.", "effects": {"auth": -1}},
    {"id": 25, "question": "The government should not be able to impose a curfew or restrict law-abiding citizens from leaving their homes.", "effects": {"auth": -1}},
    {"id": 26, "question": "The existance of prisons makes the world worse.", "effects": {"auth": -1}},
    {"id": 27, "question": "The right to trial by jury should be guaranteed to all citizens.", "effects": {"auth": -1}},
    {"id": 28, "question": "Freedom is the ability to fufil one's own desires.", "effects": {"auth": -1}},
    {"id": 29, "question": "The seperation of powers is very important.", "effects": {"auth": -1}},
    {"id": 30, "question": "It is okay to be a homosexual.", "effects": {"prog": 1}},
    {"id": 31, "question": "Some women were born with penises.", "effects": {"prog": 1}},
    {"id": 32, "question": "Openess about sex cannot go too far.", "effects": {"prog": 1}},
    {"id": 33, "question": "Decline in religiousity is a good thing.", "effects": {"prog": 1}},
    {"id": 34, "question": "Same-sex marriage should be legal.", "effects": {"prog": 1}},
    {"id": 35, "question": "Women are liberated only through a rejection of men and male constructs.", "effects": {"prog": 1}},
    {"id": 36, "question": "There is nothing wrong with a man wearing makeup and dresses in public.", "effects": {"prog": 1}},
    {"id": 37, "question": "Non-violent offenses should carry light sentences if any at all.", "effects": {"prog": 1}},
    {"id": 38, "question": "Humanity should be in communion with the past.", "effects": {"prog": -1}},
    {"id": 39, "question": "The Enlightenment and its consequences have been a disaster for the human race.", "effects": {"prog": -1}},
    {"id": 40, "question": "A theocratic form of government is ideal.", "effects": {"prog": -1}},
    {"id": 41, "question": "Being a homosexual is a choice.", "effects": {"prog": -1}},
    {"id": 42, "question": "Adultery should carry a death sentance.", "effects": {"prog": -1}},
    {"id": 43, "question": "Wives should take the surname of their husbands.", "effects": {"prog": -1}},
    {"id": 44, "question": "Some religions are better than others.", "effects": {"prog": -1}},
    {"id": 45, "question": "Religion and tradition are more trustworthy than science.", "effects": {"prog": -1}}
];
